name: Pull Requests

on:
  pull_request:
    types: [opened, synchronize, edited, ready_for_review]


jobs:
  lint-pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '(feat|chore|fix|docu):.*'
          min_length: 5
          github_token: ${{ github.token }}

  validate-yaml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: List changed files
      id: files
      uses: jitterbit/get-changed-files@v1
    - name: Install Yamllint
      run: |
        pip install --user yamllint
    - name: Lint Yaml files
      run: |
        for changed_file in ${{ steps.files.outputs.all }}; do
          yamllint ${changed_file} --no-warnings -f colored
        done
