name: Build app

on:
  pull_request:
    types: [opened, synchronize, edited, ready_for_review]


jobs:
  mystep-one:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '(feat|chore|fix|docu):.*'
          min_length: 5
          github_token: ${{ github.token }}

  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: List changed files
        id: yamlfiles
        uses: tj-actions/changed-files@v21
        with:
          files: |
            *.yaml
            *.yml
      - name: Install Yamllint
        run: |
          pip install --user yamllint
      - name: Lint Yaml files
        run: |
          for changed_file in ${{ steps.yamlfiles.outputs.all_changed_files }}; do
            yamllint -d {extends: relaxed, rules: {line-length: {max: 120},indentation: {indent-sequences: whatever},new-lines: disable,new-line-at-end-of-file: 'disable'}} ${changed_file} -f colored
          done
